Repository Eurachacha/hanmogeum, pull requests merged in 2023-11, with the labels that each got.

#4 setting(public): SUIT, MaruBuri 폰트 추가 (#3)
  public/fonts/MaruBuri-Bold.woff2
  public/fonts/MaruBuri-ExtraLight.woff2
  public/fonts/MaruBuri-Light.woff2
  public/fonts/MaruBuri-Regular.woff2
  public/fonts/MaruBuri-SemiBold.woff2
  public/fonts/SUIT-Bold.woff2
  public/fonts/SUIT-ExtraBold.woff2
  public/fonts/SUIT-ExtraLight.woff2
  public/fonts/SUIT-Heavy.woff2
  public/fonts/SUIT-Light.woff2
  public/fonts/SUIT-Medium.woff2
  public/fonts/SUIT-Regular.woff2
  public/fonts/SUIT-SemiBold.woff2
  public/fonts/SUIT-Thin.woff2
Labels: ⚙️setting

#13 feat(@/components/Button.tsx): 공용 버튼 컴포넌트 생성 (#10)
  .eslintrc
  src/components/common/Button.tsx
  src/index.css
Labels: ✨feature, 🎨UI, 🎸chore

#29 feat(@/components/common/Modal.tsx): 공통 모달 컴포넌트 생성 (#15)
  package-lock.json
  package.json
  public/icons/circleCheck.svg
  src/components/common/Modal.tsx
  src/types/svg.d.ts
  tsconfig.json
  vite.config.ts
Labels: ✨feature

#31 fix(Button.tsx): 잘못 입력한 스타일링코드 삭제 (#22)
  src/components/common/Button.tsx
Labels: 🎸chore

#35 chore(Button.tsx): interface를 import문 아래로 이동 (#32)
  src/components/common/Button.tsx
Labels: 🎸chore
