Repository Eurachacha/hanmogeum, pull requests merged in 2023-12, with the labels that each got.

#62 fix(types): products interface에 변경된 타입 반영(#60)
  src/types/products.ts
Labels: ☝🏻priority-1, 🎸chore

#63 fix(@/components): 상품 아이템 라벨 props 속성 추가(#21)
  src/components/product/ProductItemLabel.tsx
Labels: ✨feature, ✌🏻priority-2

#68 feat(cart): 장바구니 기본 기능 구현 (#34)
  .eslintrc
  src/assets/icons/cancel.svg
  src/assets/icons/checkedBox.svg
  src/assets/icons/uncheckedBox.svg
  src/components/cart/CartItem.tsx
  src/components/cart/CounterButton.tsx
  src/components/cart/Price.tsx
  src/constants/cart.ts
  src/containers/.gitkeep
  src/containers/cart/CartItemContainer.tsx
  src/containers/cart/CartItemListContainer.tsx
  src/containers/cart/CounterContainer.tsx
  src/containers/cart/PriceInfoContainer.tsx
  src/pages/CartPage.tsx
  src/types/cart.ts
Labels: ✨feature

#71 chore(cart): @/containers/cart import문 수정 (#70)
  src/components/cart/CartItem.tsx
  src/pages/CartPage.tsx
Labels: 🎸chore

#82 feat(product): 상품 아이템과 아이템 리스트 구현(#21)
  package-lock.json
  src/components/product/ProductItem.tsx
  src/components/product/ProductItemList.tsx
Labels: ✨feature, ☝🏻priority-1

#91 feat(order-checkout): 주문하기페이지 좌측 기본 마크업 완료 (#84)
  .eslintrc
  src/apis/services/cart.ts
  src/apis/services/orders.ts
  src/components/common/Button.tsx
  src/components/orderCheckout/FormInput.tsx
  src/components/orderCheckout/Info.tsx
  src/components/orderCheckout/OrderItem.tsx
  src/containers/orderCheckout/InfoContainer.tsx
  src/containers/orderCheckout/OrderListContainer.tsx
  src/containers/orderCheckout/ShippingInfoContainer.tsx
  src/pages/OrderCheckoutPage.tsx
  src/types/cart.ts
  src/types/orders.ts
Labels: ✨feature

#96 feat(hooks): 쿼리스트링 저장하는 커스터 훅 추가(#87)
  src/hooks/useQueryParams.tsx
Labels: ✨feature

#99 feat(orderCheckout): 주문하기 페이지 기본 마크업 (#84)
  src/components/common/Price.tsx
  src/components/orderCheckout/FormInput.tsx
  src/components/orderCheckout/OrderItem.tsx
  src/constants/order.ts
  src/containers/cart/CartPriceContainer.tsx
  src/containers/orderCheckout/OrderInfo.tsx
  src/containers/orderCheckout/OrderListContainer.tsx
  src/containers/orderCheckout/OrderPriceContainer.tsx
  src/containers/orderCheckout/ShippingInfoContainer.tsx
  src/containers/orderCheckout/UserInfoContainer.tsx
  src/pages/CartPage.tsx
  src/pages/OrderCheckoutPage.tsx
Labels: ✨feature, 🎨UI

#112 상품 목록 페이지 구현 마크업
  src/assets/icons/toggleActive.svg
  src/assets/icons/toggleDefault.svg
  src/components/category/CategoryButton.tsx
  src/components/category/CategoryButtonList.tsx
  src/components/category/CategoryList.tsx
  src/components/product/ProductItem.tsx
  src/components/product/ProductItemLabel.tsx
  src/components/product/ProductItemList.tsx
  src/components/product/ProductSortButtons.tsx
  src/containers/product/ProductSortContainer.tsx
  src/pages/ProductListPage.tsx
Labels: ✨feature, ✌🏻priority-2

#115 rename(components): 상품 컴포넌트 폴더 분리(#114)
  src/components/product/productlist/CategoryButton.tsx
  src/components/product/productlist/CategoryButtonList.tsx
  src/components/product/productlist/CategoryList.tsx
  src/components/product/productlist/ProductItem.tsx
  src/components/product/productlist/ProductItemLabel.tsx
  src/components/product/productlist/ProductItemList.tsx
  src/components/product/productlist/ProductSortButtons.tsx
  src/containers/product/ProductSortContainer.tsx
  src/pages/ProductListPage.tsx
Labels: 🎸chore

#120 feat(cart): 로그인 여부에 따른 장바구니 아이템 상호 작용 구현 (#119)
  src/apis/services/cart.ts
  src/components/cart/CartItem.tsx
  src/constants/cart.ts
  src/constants/localstorageKeys.ts
  src/containers/cart/CartItemContainer.tsx
  src/containers/cart/CartItemListContainer.tsx
  src/containers/cart/CounterContainer.tsx
  src/pages/CartPage.tsx
  src/recoil/.gitkeep
  src/recoil/atoms/cartState.ts
  src/types/cart.ts
  src/types/orders.ts
Labels: ✨feature

#122 feat(/apis): 토큰 만료 시 자동 로그인 연장 처리 (#116)
  src/apis/instance.ts
  src/containers/LoginContainer/LoginContainer.tsx
Labels: ✨feature

#129 feat(/apis): 정렬&필터 작업을 위한 api 함수 생성(#128)
  src/apis/services/products.ts
  src/hooks/.gitkeep
Labels: ✨feature, ☝🏻priority-1

#130 feat(cart): 로그인 여부에 따른 장바구니 금액안내 기능 구현 (#125)
  src/components/cart/CartItem.tsx
  src/containers/cart/CartItemContainer.tsx
  src/containers/cart/CartItemListContainer.tsx
  src/containers/cart/CartPriceContainer.tsx
  src/pages/CartPage.tsx
Labels: ✨feature

#141 fix(ProductList): 쿼리스트링 코드값으로 변경(#124)
  src/components/product/productlist/CategoryButtonList.tsx
Labels: 🎸chore

#157 feat(cart): 장바구니페이지 기본기능 구현 및 에러 해결
  .eslintrc
  src/apis/services/orders.ts
  src/components/cart/CartItem.tsx
  src/components/common/Header.tsx
  src/containers/LoginContainer/LoginContainer.tsx
  src/containers/SignUpContainer/SignUpContainer.tsx
  src/containers/cart/CartItemContainer.tsx
  src/containers/cart/CartItemListContainer.tsx
  src/containers/cart/CartPriceContainer.tsx
  src/pages/CartPage.tsx
  src/recoil/atoms/cartState.ts
  src/types/cart.ts
  src/types/orders.ts
  src/types/users.ts
Labels: ✨feature, 🐛bug

#159 chore(Modal): ButtonArea justify-content:center 처리 (#158)
  src/components/common/Modal.tsx
Labels: 🎸chore

#160 feat(cart): 비로그인 구매하기 클릭시 /login으로 이동 (#135)
  src/containers/cart/CartPriceContainer.tsx
Labels: ✨feature

#162 feat(cart): [로그인] 재고부족시 재고만큼 수량 update (#154)
  src/components/cart/CartItem.tsx
Labels: ✨feature

#163 feat(orderCheckout): 초기 접속시 재고 체크 후 모달 생성 (#161)
  src/containers/orderCheckout/OrderInfo.tsx
  src/containers/orderCheckout/OrderListContainer.tsx
  src/containers/orderCheckout/OrderPriceContainer.tsx
  src/pages/OrderCheckoutPage.tsx
Labels: ✨feature

#164 feat(orderCheckout): 주소찾기 기능 연결 (#83)
  src/containers/orderCheckout/ShippingInfoContainer.tsx
  src/utils/.gitkeep
Labels: ✨feature

#166 feat(orders.ts): POST /orders 요청 data 타입 수정 (#165)
  src/types/orders.ts
Labels: ✨feature

#170 feat(주문하기): 상품및배송 정보로 주문 요청 구현 (#83)
  src/containers/orderCheckout/OrderInfo.tsx
  src/containers/orderCheckout/ShippingInfoContainer.tsx
  src/pages/OrderCheckoutPage.tsx
  src/types/orders.ts
Labels: ✨feature

#179 feat(orderCheckout): 전화번호 autoHyphen 적용 (#174)
  package-lock.json
  src/containers/orderCheckout/ShippingInfoContainer.tsx
  src/containers/orderCheckout/UserInfoContainer.tsx
Labels: ✨feature

#187 feat(cart): 수량조절시 0 미만 제한 (#186)
  src/components/cart/CartItem.tsx
Labels: 🐛bug

#197 feat(cart): 비로그인 유저 장바구니 초기접속시 재고 조회요청 API 연결 (#154)
  src/apis/services/cart.ts
  src/components/cart/CartItem.tsx
  src/containers/cart/CartItemContainer.tsx
  src/containers/cart/CartItemListContainer.tsx
  src/types/cart.ts
  src/types/orders.ts
Labels: ✨feature

#207 feat(productDetail): 상품상세페이지 마크업 및 수량조절 커스텀훅 생성
  src/components/product/productlist/CategoryButton.tsx
  src/hooks/useQuantityCounter.ts
  src/pages/ProductDetailPage.tsx
Labels: ✨feature

#208 fix(cart): 비로그인상태로 접속시 무한렌더링문제 해결 (#206)
  src/containers/cart/CartItemListContainer.tsx
Labels: 🐛bug

#215 feat(cart): 로그인접속시 모두체크되지 않는 문제 해결(#214)
  src/containers/cart/CartItemListContainer.tsx
Labels: 🐛bug

#222 chore(Modal): 줄바꿈, 강조텍스트 구현 (#220)
  src/components/common/Modal.tsx
Labels: 🎸chore

#223 feat(상품상세): 바로구매 기능 구현 (#217)
  src/pages/ProductDetailPage.tsx
Labels: ✨feature

#226 fix(ProductList): 상품목록페이지 카테고리 리스트 api 작업(#225)
  src/components/product/productlist/CategoryList.tsx
Labels: 🤟🏻priority-3, 🎸chore

#227 feat(ProductList): 상품목록 카테고리에서 pack 제외(#138)
  src/components/product/productlist/CategoryList.tsx
  src/constants/category.ts
Labels: ✨feature, 🐛bug, ✌🏻priority-2

#229 fix(ProductList):카테고리 버튼 리스트 타입 수정(#138)
  src/components/product/productlist/CategoryButtonList.tsx
Labels: ✨feature, 🎸chore

#230 fix(ProductList): 불필요한 주석 삭제(#228)
  src/components/product/productlist/CategoryList.tsx
Labels: 🤟🏻priority-3, 🎸chore

#235 refactor(cart): 수량조절커스텀훅 장바구니에 연결 (#205)
  src/components/cart/CartItem.tsx
  src/hooks/useQuantityCounter.ts
Labels: ✨feature, 🔧refactor

#236 feat(cart): 선택상품금액이 0원이면 구매하기 버튼 비활성화 (#134)
  src/containers/cart/CartPriceContainer.tsx
Labels: ✨feature, 🐛bug

#240 refactor(cart): 체크박스세팅을 CartPage에서 하도록 수정(#239)
  src/containers/cart/CartItemContainer.tsx
  src/containers/cart/CartItemListContainer.tsx
  src/pages/CartPage.tsx
Labels: 🔧refactor

#245 fix(api): products api 변경된 주소 반영(#244)
  src/apis/services/products.ts
Labels: 🎸chore

#250 feat(useQuantityCounter): 재고반영여부 state 생성(#249)
  src/hooks/useQuantityCounter.ts
Labels: ✨feature

#251 feat(cart): 아이템수량이 0이될때 체크박스 상태 변화 구현(#242)
  src/components/cart/CartItem.tsx
  src/containers/cart/CartItemContainer.tsx
  src/containers/cart/CartItemListContainer.tsx
  src/pages/CartPage.tsx
Labels: ✨feature

#253 feat(상품상세): 재고가 0인 경우 수량인풋 0으로 설정(#252)
  src/pages/ProductDetailPage.tsx
Labels: ✨feature

#256 feat(cart): DB장바구니개수 변경시 cartStorage에 반영(#255)
  src/containers/cart/CartItemListContainer.tsx
Labels: ✨feature

#258 feat(header): 헤더장바구니수량 품절상품제외 후 반영(#257)
  src/components/common/Header.tsx
Labels: ✨feature

#259 fix(hooks): 디카페인 토글 클릭 시 쿼리스트링 수정(#243)
  src/hooks/useQueryParams.tsx
Labels: ☝🏻priority-1, 🎸chore

#261 fix(cart): 단일상품삭제시 수량변경및 무한렌더링해결(#260)
  src/containers/cart/CartItemContainer.tsx
Labels: 🐛bug

#262 feat(order): 구매요청시 배송준비중을 기본state로 전달(#254)
  src/apis/services/orders.ts
Labels: ✨feature

#264 feat(apis): 상품 목록 데이터 요청하는 함수 수정(#87)
  src/apis/services/products.ts
  src/components/common/Header.tsx
  src/components/product/productlist/CategoryList.tsx
  src/pages/MainPage.tsx
Labels: 🔧refactor, ☝🏻priority-1, 🎸chore

#265 feat(ProductList): 상품 목록 카테고리 클릭 시 데이터 요청(#87)
  src/containers/product/ProductSortContainer.tsx
Labels: ✨feature, ☝🏻priority-1

#267 fix(ProductList): 상품 정렬 버튼 컴포넌트에 보내는 데이터 수정(#266)
  src/components/product/productlist/ProductSortButtons.tsx
  src/containers/product/ProductSortContainer.tsx
Labels: 🎸chore

#269 fix(ProductList): 카테고리버튼 disabled 속성 추가(#216)
  src/components/product/productlist/CategoryButton.tsx
Labels: ✨feature, 🎸chore

#272 feat(EmptyMessage): 상품이없을때 출력할 컴포넌트 생성(#271)
  public/images/emptyTea.png
  src/components/common/EmptyMessage.tsx
Labels: ✨feature

#273 feat(cart): 상품이 없을 때 메시지 출력(#126)
  src/containers/cart/CartItemContainer.tsx
  src/containers/cart/CartItemListContainer.tsx
Labels: ✨feature

#274 feat(구매하기): 접속시 아이템이 없는경우 홈으로 이동(#126)
  src/containers/orderCheckout/OrderInfoContainer.tsx
  src/pages/OrderCheckoutPage.tsx
Labels: ✨feature

#275 feat(상품상세): 바로구매기능 구현(#204)
  src/containers/orderCheckout/OrderInfoContainer.tsx
  src/containers/orderCheckout/OrderListContainer.tsx
  src/containers/orderCheckout/OrderPriceContainer.tsx
  src/pages/OrderCheckoutPage.tsx
  src/pages/ProductDetailPage.tsx
  src/types/orders.ts
Labels: ✨feature

#276 feat(ProductList): 필터 버튼 클릭 시 버튼 색상 변경(#210)
  src/components/product/productlist/CategoryButton.tsx
  src/components/product/productlist/CategoryButtonList.tsx
Labels: ✨feature, ✌🏻priority-2

#278 필터링 시 상품 크기 변화 이슈 수정(#117)
  src/components/product/productlist/CategoryList.tsx
  src/components/product/productlist/ProductItem.tsx
  src/components/product/productlist/ProductSortButtons.tsx
  src/containers/product/ProductSortContainer.tsx
  src/pages/ProductListPage.tsx
Labels: 🐛bug, ☝🏻priority-1

#279 feat(ProductList): 상품 목록 페이지 조건부 렌더링 추가(#277)
  src/components/product/productlist/ProductItemList.tsx
Labels: ✨feature, 🎨UI, ✌🏻priority-2

#282 feat(ProductList): 상품 클릭 시 상품 세부로 이동(#280)
  src/components/product/productlist/ProductItem.tsx
Labels: ✨feature, ✌🏻priority-2

#299 feat(ProductList): 상품 목록 정렬 버튼 기능 구현(#268)
  src/apis/services/products.ts
  src/components/product/productlist/ProductSortButtons.tsx
  src/containers/product/ProductSortContainer.tsx
  src/hooks/useQueryParams.tsx
Labels: ✨feature, ☝🏻priority-1

#300 fix(ProductLists): 모든 상품 이동 시 발생하는 에러(#298)
  src/components/product/productlist/ProductItem.tsx
Labels: 🐛bug, ☝🏻priority-1

#302 feat(ProductList): 상품에 해당하는 라벨만 붙이기(#295)
  src/components/product/productlist/ProductItem.tsx
Labels: ✨feature, ✌🏻priority-2

#304 fix(MainPage): 메인페이지 불필요한 코드 제거(#303)
  src/pages/MainPage.tsx
Labels: 🎸chore

#307 feat(admin): react-admin 설치 및 orderDetail 타입 수정(#306)
  package-lock.json
  package.json
  src/types/orders.ts
Labels: ✨feature, ⚙️setting

#309 chore(/types): product 타입에서 shippingFees 제거 (#308)
  src/types/manage.ts
  src/types/products.ts
Labels: 🎸chore

#311 feat(admin): 관리자페이지 라우팅 수정 (#310)
  src/Router.tsx
Labels: ✨feature

#314 feat(admin): admin,seller요청 응답인터셉터 수정 (#313)
  src/apis/instance.ts
Labels: ✨feature

#315 feat(admin): dataProvider getList 함수 세팅(#312)
  src/apis/services/admin/dataProvider.ts
Labels: ✨feature

#317 feat(admin): 주문내역 불러오기(#316)
  src/components/admin/OrderList.tsx
  src/pages/ManagePage.tsx
Labels: ✨feature

#323 feat(types): product mainImages 타입 수정(#319)
  src/types/products.ts
Labels: ✨feature

#325 feat(types): manage.ts mainImages 타입 수정 (#319)
  src/types/manage.ts
Labels: ✨feature

#332 feat(admin): ManagePage에서 code정보 recoil에 저장(#331)
  src/pages/ManagePage.tsx
Labels: ✨feature

#333 feat(admin): 상품목록 불러오기(#330)
  src/components/admin/ProductList.tsx
  src/pages/ManagePage.tsx
Labels: ✨feature

#335 feat(admin): 코드value를 반환하는 함수 생성및적용(#334)
  src/components/admin/OrderList.tsx
  src/components/admin/ProductList.tsx
  src/utils/getCodeValue.ts
Labels: ✨feature

#338 fix(admin): getCodeValue.ts 내부 훅 제거(#331)
  src/components/admin/OrderList.tsx
  src/components/admin/ProductList.tsx
  src/utils/getCodeValue.ts
Labels: 🐛bug

#339 fix(apis): productsApi 내 함수명 변경(#322)
  src/apis/services/products.ts
Labels: 🎸chore

#341 fix(cart): 비로그인시 장바구니 오류 해결(#340)
  src/containers/cart/CartItemListContainer.tsx
Labels: 🐛bug

#342 fix(ProductList): product 이미지 불러오는 형식 수정(#320)
  src/components/product/productlist/ProductItem.tsx
Labels: 🐛bug

#343 fix(ProductList): 상품 아이템 개수 props로 수정(#321)
  src/components/product/productlist/ProductItemList.tsx
  src/containers/product/ProductSortContainer.tsx
Labels: 🎸chore

#345 feat(MainPage): 메인 페이지 product 컴포넌트 생성(#247)
  src/components/main/MainProductsList.tsx
  src/containers/main/MainContainer.tsx
Labels: ✨feature

#346 fix(MainPage): MainProductsList import 이름 수정(#247)
  src/containers/main/MainContainer.tsx
Labels: 🎸chore

#354 fix(상품상세): 장바구니에담기클릭시 헤더반영오류수정(#353)
  src/pages/ProductDetailPage.tsx
Labels: 🐛bug

#356 feat(admin): seller프로바이더분리및getOne,update작성(#355)
  src/apis/services/admin/sellerDataProvider.ts
  src/pages/ManagePage.tsx
Labels: ✨feature

#358 feat(admin): 관리자api요청시의 응답인터셉터 수정(#357)
  src/apis/instance.ts
Labels: ✨feature

#361 feat(admin): OrderEdit 컴포넌트 구현(#359)
  src/components/admin/OrderEdit.tsx
  src/pages/ManagePage.tsx
Labels: ✨feature

#363 feat(admin): Router.tsx SellerPage 연결(#362)
  src/Router.tsx
  src/pages/SellerPage.tsx
Labels: ✨feature

#365 feat(cart, order): 상품이미지 타입 변경내용 적용(#320)
  src/containers/orderCheckout/OrderListContainer.tsx
  src/types/cart.ts
  src/types/orders.ts
Labels: ✨feature

#366 feat(CategoryButton): props수정 및 사용코드 수정(#281)
  src/components/product/productlist/CategoryButton.tsx
  src/components/product/productlist/CategoryButtonList.tsx
  src/pages/ProductDetailPage.tsx
Labels: ✨feature

#367 feat(ShippingInfo): order테이블 detailaddress반영(#193)
  src/containers/orderCheckout/ShippingInfoContainer.tsx
Labels: ✨feature

#378 fix(ProductList): 상품 내 code 데이터 value 변경(#209)
  src/components/product/productlist/ProductItem.tsx
Labels: ✌🏻priority-2, 🎸chore

#383 fix(ProductList): 상품 목록 페이지 정렬 에러 수정(#381)
  src/containers/product/ProductSortContainer.tsx
Labels: 🐛bug, ☝🏻priority-1, 🎸chore

#387 feat(admin): 파일 업로드 인스턴스 생성(#385)
  src/apis/instance.ts
Labels: ✨feature

#391 feat(admin): 상품등록 페이지 기본 폼 생성(#389)
  src/components/admin/ProductCreate.tsx
  src/pages/SellerPage.tsx
Labels: ✨feature

#395 파일등록 기능 구현 및 상품등록 API 연결(#393)
  src/apis/services/admin/sellerDataProvider.ts
  src/types/file.ts
Labels: ✨feature

#402 feat(구매하기): order요청 에러처리(#171)
  src/components/common/Modal.tsx
  src/pages/OrderCheckoutPage.tsx
Labels: ✨feature

#404 fix(cart): 장바구니 사진깨짐오류 해결(#372)
  src/components/cart/CartItem.tsx
Labels: 🐛bug

#406 fix(cart): 재고부족 수량자동반영시 체크해제(#405)
  src/components/cart/CartItem.tsx
Labels: 🐛bug

#407 feat(cart): 장바구니 페이지 재고 안내 및 재고반영안내메시지 출력(#403)
  src/components/cart/CartItem.tsx
Labels: ✨feature

#408 fix(cart): cart상품 주문후 상품이 남아있는 오류 해결(#373)
  src/pages/OrderCheckoutPage.tsx
  src/types/orders.ts
Labels: 🐛bug

#414 fix(cart): 주문후 장바구니상품수 헤더반영 오류 해결(#410)
  src/components/common/Header.tsx
  src/pages/OrderCheckoutPage.tsx
Labels: 🐛bug

#419 fix(cart): 바로구매시 장바구니상품 반영 버그 해결(#418)
  src/pages/OrderCheckoutPage.tsx
Labels: 🐛bug

#422 fix(ProductList): 상품 value 불러오는 에러 수정(#421)
  src/components/product/productlist/ProductItem.tsx
Labels: 🐛bug, ☝🏻priority-1

#425 feat(MainPage): 메인페이지 배너 캐러셀 추가(#142)
  package-lock.json
  package.json
  src/components/common/Carousel.tsx
  src/components/main/MainBanner.tsx
Labels: ✨feature

#432 fix(cart): 수량 자동반영 후 가격안내반영 버그 해결(#415)
  src/containers/cart/CartPriceContainer.tsx
Labels: 🐛bug

#434 fix(cart): 비로그인 상품삭제시 체크박스버그해결(#433)
  src/containers/cart/CartItemContainer.tsx
  src/containers/cart/CartItemListContainer.tsx
Labels: 🐛bug

#436 fix(cart): 수량자동반영시 헤더개수반영버그 해결(#413)
  src/components/common/Header.tsx
Labels: 🐛bug

#437 fix(ProductList): 상품 아이템 하단 가려짐 이슈 해결(#429)
  src/components/product/productlist/ProductItem.tsx
Labels: 🐛bug, 🎨UI, 🎸chore

#438 fix(ProductList): 상품 아이템에 단위 코드 추가(#301)
  src/components/product/productlist/ProductItem.tsx
Labels: 🎨UI, 🎸chore

#439 feat(admin): 헤더 관리자페이지 링크 라우팅 수정(#398)
  src/Router.tsx
  src/components/common/Header.tsx
  src/pages/AdminPage.tsx
Labels: ✨feature

#442 feat(상품상세): 메인이미지및 상세정보 출력(#441)
  src/pages/ProductDetailPage.tsx
Labels: ✨feature

#446 feat(seller): 상품삭제기능 구현
  src/apis/instance.ts
  src/apis/services/admin/sellerDataProvider.ts
Labels: ✨feature

#450 design(font): 웹폰트적용 오류 해결 및 pretendard폰트 적용(#424)
  public/fonts/MaruBuri-Bold.woff2
  public/fonts/MaruBuri-ExtraLight.woff2
  public/fonts/MaruBuri-Light.woff2
  public/fonts/MaruBuri-Regular.woff2
  public/fonts/MaruBuri-SemiBold.woff2
  public/fonts/Pretendard-Black.woff2
  public/fonts/Pretendard-Bold.woff2
  public/fonts/Pretendard-ExtraBold.woff2
  public/fonts/Pretendard-ExtraLight.woff2
  public/fonts/Pretendard-Light.woff2
  public/fonts/Pretendard-Medium.woff2
  public/fonts/Pretendard-Regular.woff2
  public/fonts/Pretendard-SemiBold.woff2
  public/fonts/Pretendard-Thin.woff2
  public/fonts/SUIT-Bold.woff2
  public/fonts/SUIT-ExtraBold.woff2
  public/fonts/SUIT-ExtraLight.woff2
  public/fonts/SUIT-Heavy.woff2
  public/fonts/SUIT-Light.woff2
  public/fonts/SUIT-Medium.woff2
  public/fonts/SUIT-Regular.woff2
  public/fonts/SUIT-SemiBold.woff2
  public/fonts/SUIT-Thin.woff2
  src/components/cart/CounterButton.tsx
  src/components/common/Button.tsx
  src/components/common/Header.tsx
  src/components/product/productlist/CategoryList.tsx
  src/index.css
  src/styles/global.css
  src/styles/reset.css
Labels: 🐛bug, 🎨UI

#452 ProductItem 컴포넌트 UI 수정(#449)
  src/components/product/productlist/ProductItem.tsx
  src/components/product/productlist/ProductItemList.tsx
Labels: 🐛bug, 🎨UI, 🎸chore

#456 main에서 axios타임아웃 주석처리한 내용 dev에도 반영
  src/apis/instance.ts
Labels: 🎸chore

#466 필터링 관련 오류 해결
  src/components/product/productlist/CategoryList.tsx
  src/containers/product/ProductSortContainer.tsx
Labels: 🐛bug, ☝🏻priority-1

#472 메인 페이지 구현(#471)
  public/images/banner_001.png
  public/images/banner_002.png
  src/Router.tsx
  src/apis/services/products.ts
  src/components/common/Button.tsx
  src/components/common/Carousel.tsx
  src/components/main/Banner.tsx
  src/components/main/MainBanner.tsx
  src/components/main/MainProductsList.tsx
  src/components/recommend/ScrollProgressbar.tsx
  src/components/recommend/TeaSurvey.tsx
  src/containers/main/MainContainer.tsx
  src/pages/MainPage.tsx
  src/pages/RecommendPage.tsx
  src/pages/TeaSurveyResultPage.tsx
Labels: ✨feature, 🎸chore

#474 feat(ErrorPage): 에러페이지 디자인 및 구현(#286)
  src/pages/ErrorPage.tsx
Labels: ✨feature, 🎨UI, ✌🏻priority-2

#482 fix(seller): 상품이미지 수정 버그 해결(#481)
  src/apis/services/admin/sellerDataProvider.ts
  src/components/admin/ProductEdit.tsx
Labels: 🐛bug

#484 fix(ProductList): 카테고리 상단 제목 변경(#470)
  src/components/product/productlist/CategoryList.tsx
Labels: 🎸chore

#488 fix(MainPage): 메인페이지 배너 디자인 수정(#471)
  public/images/banner_003.png
  src/components/main/Banner.tsx
  src/components/main/MainBanner.tsx
Labels: 🎨UI, 🎸chore

#489 design(seller): 주문관리, 주문상세 페이지 스타일링
  src/components/admin/OrderEdit.tsx
  src/components/admin/OrderList.tsx
  src/components/admin/ProductList.tsx
Labels: 🎨UI

#491 Feat/main products
  src/components/product/productlist/CategoryList.tsx
  src/components/recommend/ScrollProgressbar.tsx
Labels: 🐛bug, 🎸chore

#492 feat(App.tsx): ScrollTop 적용(#420)
  src/App.tsx
  src/components/common/ScrollTop.tsx
Labels: ✨feature

#496 버전 1.0.0 메인 머지
  package-lock.json
  package.json
  public/images/banner_001.png
  public/images/banner_002.png
  public/images/banner_003.png
  src/App.tsx
  src/Router.tsx
  src/apis/services/admin/sellerDataProvider.ts
  src/apis/services/products.ts
  src/components/MypageDashBoard/WidgetMyInfo.tsx
  src/components/MypageDashBoard/WidgetShipping.tsx
  src/components/MypageDashBoard/WidgetTodayTea.tsx
  src/components/admin/OrderEdit.tsx
  src/components/admin/OrderList.tsx
  src/components/admin/ProductEdit.tsx
  src/components/admin/ProductList.tsx
  src/components/common/Button.tsx
  src/components/common/Carousel.tsx
  src/components/common/Footer.tsx
  src/components/common/Header.tsx
  src/components/common/Input.tsx
  src/components/common/LoadingSpinner.tsx
  src/components/common/ScrollTop.tsx
  src/components/contentsTitle/ContentsTitle.tsx
  src/components/itemInput/ItemInput.tsx
  src/components/login/Login.tsx
  src/components/main/Banner.tsx
  src/components/main/MainBanner.tsx
  src/components/main/MainProductsList.tsx
  src/components/mypage/ContainerHeader..tsx
  src/components/mypage/NavigationMenu.tsx
  src/components/mypage/OrderDetailInfo.tsx
  src/components/mypage/OrderItemContentsText.tsx
  src/components/product/productlist/CategoryList.tsx
  src/components/product/productlist/ProductItem.tsx
  src/components/recommend/ScrollProgressbar.tsx
  src/components/recommend/TeaSurvey.tsx
  src/components/route/ProtectedRoute.tsx
  src/constants/code.ts
  src/containers/main/MainContainer.tsx
  src/containers/mypage/MyOrderDetailContainer.tsx
  src/containers/mypage/MyOrderListContainer.tsx
  src/containers/mypage/MyProfileLoginContainer.tsx
  src/containers/mypage/MyProfileModifyContainer.tsx
  src/containers/orderCheckout/ShippingInfoContainer.tsx
  src/containers/product/ProductSortContainer.tsx
  src/containers/signUp/SignUpContainer.tsx
  src/pages/ErrorPage.tsx
  src/pages/MainPage.tsx
  src/pages/RecommendPage.tsx
  src/pages/SellerPage.tsx
  src/pages/TeaSurveyResultPage.tsx
  src/types/file.ts
Labels: 🔗deploy

#501 버전 1.0.1 메인 머지
  README.md
  src/components/common/Modal.tsx
Labels: 🔗deploy

#506 design(seller): 상품상세및수정 페이지 스타일링(#483)
  src/components/admin/ProductEdit.tsx
Labels: 🎨UI

#507 fix(seller): teaType, pack을 배열로 저장하도록 수정(#505)
  src/apis/services/admin/sellerDataProvider.ts
Labels: 🐛bug

#509 fix(seller): 상품수정중 file 필드가 없을시 리턴(#508)
  src/apis/services/admin/sellerDataProvider.ts
Labels: 🐛bug

#511 fix(seller): 상품등록,상품수정 validate오류 해결(#479)
  src/components/admin/ProductCreate.tsx
  src/components/admin/ProductEdit.tsx
Labels: 🐛bug

#513 fix(ErrorPage): 홈으로돌아가기 replace처리(#512)
  src/pages/ErrorPage.tsx
Labels: 🎸chore

#516 refactor(ProductList): 상품목록페이지 react-query 도입(#515)
  src/containers/product/ProductSortContainer.tsx
Labels: 🔧refactor

#518 fix(ProductList): error 처리 코드 추가(#515)
  src/containers/product/ProductSortContainer.tsx
Labels: 🎸chore

#520 버전 1.0.2 메인 merge
  src/apis/services/admin/sellerDataProvider.ts
  src/components/admin/ProductCreate.tsx
  src/components/admin/ProductEdit.tsx
  src/containers/mypage/MyOrderDetailContainer.tsx
  src/containers/product/ProductSortContainer.tsx
  src/pages/ErrorPage.tsx
Labels: 🔗deploy

#525 fix(구매하기): 장바구니수량이0일때 바로구매 오류 해결(#524)
  src/containers/orderCheckout/OrderListContainer.tsx
  src/pages/OrderCheckoutPage.tsx
Labels: 🐛bug

#530 fix(ProductList): 선택한 정렬버튼 CSS 추가(#517)
  src/components/product/productlist/ProductSortButtons.tsx
Labels: ✨feature, 🎨UI

#540 feat(token): 토큰 리프레시 요청 실패시 로그아웃 처리(#462)
  src/App.tsx
  src/apis/instance.ts
  src/components/common/LoadingSpinner.tsx
  src/components/common/TokenExpireModal.tsx
  src/hooks/useAxiosInterceptor.ts
  src/pages/AdminPage.tsx
  src/pages/SellerPage.tsx
  src/recoil/atoms/tokenExpireModalState.ts
Labels: ✨feature

#543 feat(상품상세): 반응형 구현 및 유저 상호작용부 fixed처리(#542)
  src/pages/ProductDetailPage.tsx
Labels: 🎨UI

#546 feat(상품상세): 로딩,캐싱 처리를위한 리액트쿼리도입(#541)
  src/pages/ProductDetailPage.tsx
Labels: ✨feature

#548 fix(seller): 상품등록및수정 validation 오류 해결(#547)
  src/components/admin/ProductCreate.tsx
  src/components/admin/ProductEdit.tsx
Labels: 🐛bug

#550 feat(seller): 상품관리, 주문관리 페이지네이션(#549)
  src/apis/services/admin/sellerDataProvider.ts
  src/components/admin/OrderList.tsx
  src/components/admin/ProductList.tsx
Labels: ✨feature

#552 feat(seller): 판매관리페이지 정렬기능 구현(#551)
  src/components/admin/OrderEdit.tsx
  src/components/admin/OrderList.tsx
  src/components/admin/ProductList.tsx
Labels: ✨feature

#554 design(seller): 타이틀 및 좌측메뉴 스타일링(#553)
  src/components/admin/SideMenu.tsx
  src/pages/SellerPage.tsx
Labels: 🎨UI

#556 fix(구매하기): 배송정보 validation버그 해결(#555)
  src/containers/orderCheckout/ShippingInfoContainer.tsx
  src/pages/OrderCheckoutPage.tsx
Labels: 🐛bug

#558 fix(seller): 상품 이미지 등록 오류 해결(#557)
  src/apis/services/admin/sellerDataProvider.ts
Labels: 🐛bug

#560 feat(상품상세): 메인, 상세이미지 사이 컨텐츠 추가(#461)
  public/images/blackSticker.png
  src/components/productDetail/CategoryInfo.tsx
  src/pages/ProductDetailPage.tsx
Labels: ✨feature

#562 fix(CategoryInfo): map함수 리턴태그 key값 추가(#561)
  src/components/productDetail/CategoryInfo.tsx
Labels: 🐛bug

#563 feat(TeaSurvey): 추천페이지 작업(#360)
  src/components/recommend/TeaSurvey.tsx
  src/pages/TeaSurveyResultPage.tsx
Labels: ✨feature

#567 feat(seller): 상품수정페이지 누적판매량 출력(#566)
  src/components/admin/ProductEdit.tsx
Labels: ✨feature

#569 fix(ProductList): 상품목록아이템 hover 시 taste 추가(#449)
  src/components/product/productlist/ProductItem.tsx
Labels: 🎨UI, 🔧refactor

#570 feat(seller): 상품공개여부 수정 구현 및 list출력(#568)
  src/components/admin/ProductCreate.tsx
  src/components/admin/ProductEdit.tsx
  src/components/admin/ProductList.tsx
Labels: ✨feature
